# Site
repository: garronej/resume
favicon: images/favicon.ico
baseurl: "/resume"

# Personal info
name: Joseph Garrone
title: Ingénieur logiciel / Architecte logiciel
email: joseph.garrone@protonmail.com
phone: +33 6 36 78 63 85
#website: https://garronej.github.io/resume

# Dark Mode (true/false/never)
darkmode: never

# Social links
#twitter_username: GarroneJoseph
github_username: garronej
linkedin_username: joseph-garrone-0b583490

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Profil
about_profile_image: images/profile.png
about_content: |
  Ingénieur logiciel avec plus de 10 ans d'expérience, je suis l'un des contributeurs open source les plus actifs de France, comme en témoigne ma participation sur [GitHub](https://github.com/garronej#js-contribution-activity).  
  Classé 3e au niveau mondial parmi les experts TypeScript sur [CodersRank](https://profile.codersrank.io/leaderboard/developer?technology=TypeScript), j'ai une présence significative dans la communauté avec mes bibliothèques open source, téléchargées plus d'un million de fois chaque mois.  

# Projects Section
#projects_title: Open source work highlights

# Experience Section
experience_title: Expérience professionnelle

oss_experience_title: Projets open source
oss_experience_description: |
  Sélection non exhaustive de projets open source largement réutilisés dans l'industrie.  

# Education Section
education_title: Études

skills_title: Domaines d'expertise
skills_content: |
  - Architecture et développement logiciel : Frontend, Backend, CLI et embarqué.
    Langages de prédilection : TypeScript et Java.
  - Automatisation CI/CD, packaging, déploiement.
  - Sécurité informatique, Keycloak, méthodes de chiffrement.
  - Mise en production d'applications : Kubernetes, Docker.
  - Conception et gestion de bases de données relationnelles.
  - Gestion de projets open source et de communautés.
  - Connaissance approfondie des réseaux et des protocoles.
  - Théorie des langages, compilation, interprétation.
  - Production de contenu technique : documentation, tutoriels.
  - Création de vidéos promotionnelles.
  - Solide base de connaissances mathématiques.  

# More Section
more_title: Langues
more_content: | # this will include new lines to allow paragraphs
  Professionnellement, je communique principalement en anglais.  
  Pour évaluer mon aisance à l'oral, vous pouvez [consulter ce vlog](https://youtu.be/Ou2I4oWuUj8?si=1hnHjlsXzj4MY9kK).  
  Je comprends également l'espagnol et suis capable de communiquer dans cette langue.  

# Footer
footer_show_references: false

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
