# Site
repository: garronej/resume
favicon: images/favicon.ico
baseurl: "/resume"

# Personal info
name: Joseph Garrone
title: Ingénieur logiciel / Architecte logiciel
email: joseph.garrone@protonmail.com
phone: +33 6 36 78 63 85
website: https://garronej.github.io/resume

# Dark Mode (true/false/never)
darkmode: never

# Social links
#twitter_username: GarroneJoseph
github_username:  garronej
linkedin_username: joseph-garrone-0b583490

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Profile
about_profile_image: images/profile.png
about_content: |
  Je suis un ingénieur logiciel avec [plus de 10 ans d'expérience](https://github.com/garronej#js-contribution-activity).  
  Je suis [fait parti des contributeurs open source les plus actif de France](https://committers.top/france).  
  Je figure en 3e position dans [le classement mondial des experts TypeScript](https://profile.codersrank.io/leaderboard/developer?technology=TypeScript) 
  de CodersRank (parmi plus de 116 000).  
  Mes bibliothèques open source sont [téléchargées plus d'un million de fois chaque mois](https://npm-stat.com/charts.html?author=garronej&from=2020-02-01&to=2024-01-31).  

# Projects Section
#projects_title: Open source work highlights

# Experience Section
experience_title: Experience professionnel

oss_experience_title: Projets open sources
oss_experience_description: |
  Séléction non exhaustives de projets open source largement réutilisé dans l'industrie.  

# Education Section
education_title: Etudes 


skills_title: Domaine d'expertise
skills_content: |
  - Architecture logicielle
  - Développement logiciel, Frontend, Backend, CLI et embarqué.  
    Langage privilégier: TypeScript et Java.  
  - CI/CD automatisation, packaging, déploiement.
  - Sécurité informatique, Keycloak, methodes d'encription.  
  - Mise en production d'applicatif: Kubernetes, Docker.  
  - Concéption et géstioin de base de données relationnelles.  
  - Pilotage de projet open source et de communautées.  
  - Connaissance approfondie des réseaux et des protocoles.  
  - Théorie des langages, compilation, interprétation.  
  - Production de contenu technique, documentation, tutoriels.  
  - Réalisation de vidéos promotionelles.  
  - Socle de conaissance mathematique solide.  

# More Section
more_title: Langues
more_content: | # this will include new lines to allow paragraphs
  Dans un contexte professionnel, je communique principalement en anglais.  
  Si vous désiez évaluer mon niveau d'aisance a l'oral vous pouvez [consulter ce vlog](https://youtu.be/Ou2I4oWuUj8?si=1hnHjlsXzj4MY9kK).  
  Je comprends et parle également l'espagnol.  

# Footer
footer_show_references: false

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
