# Site
repository: garronej/resume
favicon: images/favicon.ico

# Personal info
name: Joseph Garrone
title: Software engineer
email: joseph.garrone@protonmail.com
phone: +33 6 36 78 63 85
website: https://garronej.github.io/resume

# Dark Mode (true/false/never)
darkmode: never

# Social links
twitter_username: GarroneJoseph
github_username:  garronej
linkedin_username: joseph-garrone-0b583490

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: |
  Hello, I am a full-stack software engineer and there are my professional guidelines:
  - Write Software that can be easily maintained.  
  - Build products that can evolve on the long run.  
  - Never solve the same problem twice.  
  - The end user experience is, if not the only, the n°1 focus.

  I achieve this by:
  - Automating everything that can be using CI/CD and containerization.
  - Caring a great deal about software architecture. Writing code decoupled, implementing Clean Archi.
  - Rigorous implementation of strict typing and testing.
  - Solving problems in isolation, writing documentation for my future self and the community and opensourcing.

  I choose to focus on the JavaScript ecosystem because it's the only language that run's everywhere 
  and I believe there are great benefits in using the same stack for backend frontend and scripting. 


# Projects Section
projects_title: Open source work highlights

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
more_title: Languages
more_content: | # this will include new lines to allow paragraphs
  - Mother tongue is __French__
  - I am fluent in __English__ although my phonetic is terrible and my speech rate is slow.
  - Fluent in __Spanish__ as well I but have few occasions to practice, I might be a bit rusty
  - I am dyslexic, my spelling is terrible but [Antidote](https://www.antidote.info/fr) does wonders.

skills_title: Skills
skills_content: |
  #### Programming paradigm
  I favor functional over object oriented and I can write an essay explaining why
  but I happily work on OOP codebase when required to. 

  #### JS Runtimes 
  I know well all major JavaScript runtime: 
  Node.js, Browsers, ReactNative, LiquidCore, Deno  

  #### Front-end frameworks
  I can build my own UI framework from scratch but I use React (or whatever is in place) because the wheel does not need to be reinvented.  

  #### System security and Cryptography
  I know how to implement symmetrical and asymmetrical encryption.  
  Writing secure code is a major interest for me, I know and understand most of the common
  vulnerabilities in IT systems.

  #### System administration
  I prefer working using k8s and docker but I know UNIX system enough
  to deploy services without containerization. I am good at scripting.  
  I have have a lot of experience with AWS.

  #### Language Theory
  I can write compilers and interpreters.

  #### Databases
  I know how to design and query complex relational databases.  
  If given the choice, I use MySQL.

  #### Devops
  I know how to implement CD/CI. I know GitHub Actions features well.

  #### Network engineering
  Deep understanding of the TCP/IP stack and of how the web works in general.  
  I can implements complex network protocol from RFC specs.

  #### Languages with which I have a real expertise (try me)
  JavaScript, TypeScript

  #### Language with which I can be efficient on day one
  Java, C

  #### Languages with which I have some experience but I would need a couple of week to get fully efficient with
  C#, Python, C++, ADA, R, Matlab


# Footer
footer_show_references: false

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
